services:

  web:
    build:
      context: .
      target: base
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/symfony_db?serverVersion=16&charset=utf8
    ports:
      - 8080:80
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=symfony_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
