name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: action/checkout
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)