name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v4
    
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag chocolatine:$(date +%s) --tag chocolatine:latest

    - name: Testing
      run: docker run -t chocolatine:latest php /app/bin/phpunit